GET http://localhost:3001/api/items

###
GET http://localhost:3001/api/orders/1

###
POST http://localhost:3001/api/orders
content-type: application/json

{
    "name": "foo bar",
    "email": "abc@ef.com",
    "phone": "1233321322",
    "items":[{
        "item":{
            "id": 1,
            "price": 12
            },
        "amount": 2
        }
    ]
}